title: "Haijun Gong"
email: "haijun.gong@slu.edu"
description: "Professor of Statistics"
baseurl: ""
url: "https://gongdata.github.io"
theme: minima
collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
